apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app
spec:
  replicas: 2
  spec:
    containers:
      name: app
      image: app
      imagePullPolicy: Always
      ports:
        name: http
        containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: app
    type: LoadBalancer
