apiVersion: v1
kind: Pod
metadata:
  name: podteste
  labels:
    app: teste
spec:
  - name: testedocker 
    image: app:v1
    ports:
      - containerPort: 80
  - name: nginx1
    image: nginx
    ports:
      - containerPort: 88

  